<a href="https://colab.research.google.com/github/kidujm/laptop-data-analysis/blob/main/%EB%8B%A4%EB%82%98%EC%99%80_0319.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
다나와2 = pd.read_csv('danawa_cleaned_V1 (2).csv')

In [ ]:
다나와2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864 entries, 0 to 863
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   제품명        864 non-null    object
 1   브랜드        864 non-null    object
 2   CPU브랜드     844 non-null    object
 3   CPU등급      831 non-null    object
 4   그래픽        864 non-null    object
 5   OS         864 non-null    object
 6   별점         571 non-null    float64
 7   배터리용량      864 non-null    float64
 8   무게(kg)     864 non-null    float64
 9   가격         864 non-null    int64
 10  RAM(GB)    864 non-null    float64
 11  AI여부       864 non-null    int64
 12  화면크기(인치)   864 non-null    float64
 13  용도         864 non-null    object
 14  리뷰수        864 non-null    int64
 15  용도_게임용     864 non-null    int64
 16  용도_그래픽작업용  864 non-null    int64
 17  용도_사무      864 non-null    int64
 18  용도_휴대용     864 non-null    int64
dtypes: float64(5), int64(7), object(7)
memory usage: 128.4+ KB

In [ ]:
다나와2['브랜드'].value_counts()

브랜드
MSI         306
LG전자        176
ASUS        122
레노버          77
HP           67
삼성전자         54
에이서          21
APPLE        16
Razer        16
DELL          6
GIGABYTE      3
Name: count, dtype: int64

In [ ]:
len(다나와2.loc[다나와2['리뷰수'] == 0])

293

In [ ]:
다나와2[다나와2['리뷰수'] == 0]['브랜드'].value_counts()

브랜드
LG전자     91
ASUS     68
레노버      50
HP       31
삼성전자     18
APPLE    12
에이서      10
Razer     8
DELL      5
Name: count, dtype: int64

In [ ]:
다나와2 = 다나와2[[
    # 제품 식별 메타데이터
    '제품명', '브랜드', 'AI여부',
    # 하드웨어 사양
    'CPU브랜드', 'CPU등급', '그래픽', 'RAM(GB)', 'OS',
    # 물리 스펙
    '배터리용량', '무게(kg)', '화면크기(인치)', '가격',
    # 사용자 평가
    '별점', '리뷰수',
    # 용도
    '용도', '용도_게임용', '용도_그래픽작업용', '용도_사무', '용도_휴대용'
]]

In [ ]:
다나와2

,제품명,브랜드,AI여부,CPU브랜드,CPU등급,그래픽,RAM(GB),OS,배터리용량,무게(kg),화면크기(인치),가격,별점,리뷰수,용도,용도_게임용,용도_그래픽작업용,용도_사무,용도_휴대용
0,LG전자 2026 그램 프로16 16Z90U-KU7WK,LG전자,1,인텔,울트라7,내장,32.0,윈도우11,77.0,1.190,16.0,3199000,4.9,102,사무,0,0,1,0
1,LG전자 2025 그램 프로16 16Z90TS-GU7WK,LG전자,1,인텔,울트라7,내장,32.0,윈도우11,77.0,1.199,16.0,2489990,4.9,148,사무,0,0,1,0
2,HP 오멘 16-ap0117AX,HP,0,AMD,Ryzen9,외장,32.0,프리도스,83.0,2.350,16.0,2399000,4.8,31,"게임용 , 그래픽작업용",1,1,0,0
3,에이서 프레데터 헬리오스 네오 16 AI PHN16-73-9797,에이서,1,인텔,울트라9,외장,32.0,프리도스,90.0,2.450,16.0,2893000,5.0,7,"게임용 , 그래픽작업용",1,1,0,0
4,레노버 LEGION 5 15IRX10 i7 5060,레노버,0,인텔,i7,외장,16.0,프리도스,80.0,1.900,15.1,1969000,4.6,43,"게임용 , 그래픽작업용",1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,ASUS Gaming V16 V3607VM-RP006,ASUS,0,인텔,코어7,외장,16.0,프리도스,63.0,1.950,16.0,1755000,4.0,2,게임용,1,0,0,0
860,HP 오멘 MAX 16-ah0159TX,HP,1,인텔,울트라9,외장,32.0,윈도우11,83.0,2.490,16.0,3145000,NaN,0,"게임용 , 그래픽작업용",1,1,0,0
861,LG전자 2024 그램 프로16 16ZD90SP-GX56K,LG전자,1,인텔,울트라5,내장,16.0,프리도스,77.0,1.199,16.0,1805990,5.0,7,사무,0,0,1,0
862,LG전자 2023 울트라PC 15UD50R-GX56K WIN11,LG전자,0,인텔,i5,내장,8.0,윈도우11,49.0,1.800,15.6,929230,4.5,4,사무,0,0,1,0
863,LG전자 2023 그램15 15ZD90RU-GX56K,LG전자,0,인텔,i5,내장,16.0,프리도스,80.0,1.140,15.6,1553240,4.8,17,사무,0,0,1,0

In [ ]:
다나와2.describe()

,별점,배터리용량,무게(kg),가격,RAM(GB),AI여부,화면크기(인치),리뷰수,용도_게임용,용도_그래픽작업용,용도_사무,용도_휴대용
count,571.000000,864.000000,864.000000,8.640000e+02,864.000000,864.000000,864.000000,864.000000,864.000000,864.000000,864.000000,864.000000
mean,4.737128,72.116516,1.966774,2.442770e+06,28.224537,0.543981,15.921528,7.939815,0.586806,0.454861,0.390046,0.042824
std,0.537983,15.808497,0.586798,1.034365e+06,15.425688,0.498350,1.019224,39.388296,0.492692,0.498247,0.488043,0.202578
min,1.000000,38.000000,0.972000,6.260000e+05,8.000000,0.000000,13.300000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.700000,54.900000,1.487500,1.748668e+06,16.000000,0.000000,15.600000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,5.000000,73.000000,1.900000,2.269500e+06,32.000000,1.000000,16.000000,1.000000,1.000000,0.000000,0.000000,0.000000
75%,5.000000,86.000000,2.450000,2.898882e+06,32.000000,1.000000,16.000000,3.000000,1.000000,1.000000,1.000000,0.000000
max,5.000000,100.000000,4.340000,7.236000e+06,128.000000,1.000000,18.400000,523.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
다나와2.groupby('브랜드')['별점'].mean()

브랜드
APPLE       4.900000
ASUS        4.674074
DELL        4.600000
GIGABYTE    4.866667
HP          4.863889
LG전자        4.781176
MSI         4.698366
Razer       4.962500
레노버         4.777778
삼성전자        4.833333
에이서         4.709091
Name: 별점, dtype: float64

In [ ]:
# 1) 별점 있음 여부를 별도 피처로 생성
다나와2['has_rating'] = 다나와2['별점'].notna().astype(int)

# 2) 별점 결측은 0으로 채우되, has_rating 피처로 구분
다나와2['별점_filled'] = 다나와2['별점'].fillna(0)

/tmp/ipykernel_151/3361649286.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  다나와2['has_rating'] = 다나와2['별점'].notna().astype(int)
/tmp/ipykernel_151/3361649286.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  다나와2['별점_filled'] = 다나와2['별점'].fillna(0)

In [ ]:
다나와2.drop(columns='별점_filled', inplace=True)

/tmp/ipykernel_151/3708424791.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  다나와2.drop(columns='별점_filled', inplace=True)

In [ ]:
다나와2['CPU등급'].value_counts()
#

CPU등급
i7            149
울트라7          124
울트라5           95
울트라9           81
Ryzen7         71
i5             67
i9             67
라이젠AI 7        37
Ryzen9         36
라이젠AI 5        32
Ryzen5         30
라이젠AI 9        14
코어5            11
코어7             8
라이젠AI Max+      6
i3              2
라이젠AI Max       1
Name: count, dtype: int64

In [ ]:
다나와2[다나와2['브랜드'] == 'APPLE']
# 브랜드가 APPLE인 데이터는 그 행의 CPU브랜드를 APPLE로 대체
# 애플제품의 CPU등급은 제품명에서 추출

,제품명,브랜드,AI여부,CPU브랜드,CPU등급,그래픽,RAM(GB),OS,배터리용량,무게(kg),화면크기(인치),가격,리뷰수,용도,용도_게임용,용도_그래픽작업용,용도_사무,용도_휴대용,has_rating,별점
22,"APPLE 맥북프로14 M5프로 15코어 CPU, 16코어 GPU 실버",APPLE,0,NaN,NaN,내장,24.0,macOS,72.4,1.60,14.2,3489890,0,그래픽작업용,0,1,0,0,0,0.0
26,"APPLE 맥북프로14 M5 10코어 CPU, 10코어 GPU 블랙",APPLE,0,NaN,NaN,내장,16.0,macOS,72.4,1.55,14.2,2501690,2,그래픽작업용,0,1,0,0,1,5.0
32,"APPLE 맥북프로14 M5프로 15코어 CPU, 16코어 GPU 블랙",APPLE,0,NaN,NaN,내장,24.0,macOS,72.4,1.60,14.2,3420200,0,그래픽작업용,0,1,0,0,0,0.0
38,"APPLE 맥북프로16 M5프로 18코어 CPU, 20코어 GPU 실버",APPLE,0,NaN,NaN,내장,24.0,macOS,100.0,2.14,16.2,4289890,0,그래픽작업용,0,1,0,0,0,0.0
389,"APPLE 맥북프로14 M5 10코어 CPU, 10코어 GPU 실버",APPLE,0,NaN,NaN,내장,16.0,macOS,72.4,1.55,14.2,2501700,5,그래픽작업용,0,1,0,0,1,4.8
416,"APPLE 맥북프로14 M5 10코어 CPU, 10코어 GPU 실버 영문",APPLE,0,NaN,NaN,내장,16.0,macOS,72.4,1.55,14.2,2501700,0,그래픽작업용,0,1,0,0,0,0.0
437,"APPLE 맥북프로16 M5프로 18코어 CPU, 20코어 GPU 블랙",APPLE,0,NaN,NaN,내장,24.0,macOS,100.0,2.14,16.2,4289890,0,그래픽작업용,0,1,0,0,0,0.0
475,"APPLE 맥북프로14 M3프로 12코어 CPU, 18코어 GPU 블랙",APPLE,1,NaN,NaN,내장,18.0,macOS,72.4,1.61,14.2,2476610,110,그래픽작업용,0,1,0,0,1,4.9
485,"APPLE 맥북프로14 M5 10코어 CPU, 10코어 GPU 블랙 영문",APPLE,0,NaN,NaN,내장,16.0,macOS,72.4,1.55,14.2,2501700,0,그래픽작업용,0,1,0,0,0,0.0
494,"APPLE 맥북에어13 M5 10코어 CPU, 10코어 GPU 블루",APPLE,0,NaN,NaN,내장,16.0,macOS,53.8,1.23,13.6,2048200,0,"그래픽작업용 , 사무",0,1,1,0,0,0.0
508,"APPLE 맥북에어15 M3 8코어 CPU, 10코어 GPU 블루",APPLE,1,NaN,NaN,내장,8.0,macOS,66.5,1.51,15.3,2064790,0,그래픽작업용,0,1,0,0,0,0.0
535,"APPLE 맥북프로14 M4프로 14코어 CPU, 20코어 GPU 블랙",APPLE,1,NaN,NaN,내장,24.0,macOS,72.4,1.60,14.2,3306520,74,그래픽작업용,0,1,0,0,1,4.9
586,"APPLE 맥북에어13 M2 8코어 CPU, 10코어 GPU 블루",APPLE,1,NaN,NaN,내장,16.0,macOS,52.6,1.24,13.6,1559990,0,"그래픽작업용 , 휴대용",0,1,0,1,0,0.0
714,"APPLE 맥북프로16 M4프로 14코어 CPU, 20코어 GPU 실버",APPLE,1,NaN,NaN,내장,48.0,macOS,100.0,2.14,16.2,4590000,0,그래픽작업용,0,1,0,0,0,0.0
821,"APPLE 맥북에어15 M5 10코어 CPU, 10코어 GPU 실버",APPLE,0,NaN,NaN,내장,16.0,macOS,66.5,1.51,15.3,2342200,0,"그래픽작업용 , 사무",0,1,1,0,0,0.0
822,"APPLE 맥북에어13 M5 10코어 CPU, 10코어 GPU 실버",APPLE,0,NaN,NaN,내장,16.0,macOS,53.8,1.23,13.6,2048200,0,"그래픽작업용 , 사무",0,1,1,0,0,0.0

In [ ]:
cpu_grade_map = {
    # 인텔 구세대
    'i3': 3, 'i5': 5, 'i7': 7, 'i9': 9,
    # 인텔 코어 시리즈
    '코어5': 5, '코어7': 7,
    # 인텔 울트라 시리즈
    '울트라5': 5, '울트라7': 7, '울트라9': 9,
    # AMD 라이젠 구세대
    'Ryzen3': 3, 'Ryzen5': 5, 'Ryzen7': 7, 'Ryzen9': 9,
    # AMD 라이젠AI 시리즈
    '라이젠AI 5': 5, '라이젠AI 7': 7, '라이젠AI 9': 9,
    '라이젠AI Max': 9, '라이젠AI Max+': 9,
    # 애플 M 시리즈 (CPU브랜드가 'APPLE'인 경우)
    #'M2': 5, 'M4': 7, 'M5': 9,
}

다나와2['CPU등급'] = 다나와2['CPU등급'].map(cpu_grade_map)

# 확인
다나와2

/tmp/ipykernel_151/2625978813.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  다나와2['CPU등급'] = 다나와2['CPU등급'].map(cpu_grade_map)

,제품명,브랜드,AI여부,CPU브랜드,CPU등급,그래픽,RAM(GB),OS,배터리용량,무게(kg),화면크기(인치),가격,리뷰수,용도,용도_게임용,용도_그래픽작업용,용도_사무,용도_휴대용,has_rating,별점
0,LG전자 2026 그램 프로16 16Z90U-KU7WK,LG전자,1,인텔,7.0,내장,32.0,윈도우11,77.0,1.190,16.0,3199000,102,사무,0,0,1,0,1,4.9
1,LG전자 2025 그램 프로16 16Z90TS-GU7WK,LG전자,1,인텔,7.0,내장,32.0,윈도우11,77.0,1.199,16.0,2489990,148,사무,0,0,1,0,1,4.9
2,HP 오멘 16-ap0117AX,HP,0,AMD,9.0,외장,32.0,프리도스,83.0,2.350,16.0,2399000,31,"게임용 , 그래픽작업용",1,1,0,0,1,4.8
3,에이서 프레데터 헬리오스 네오 16 AI PHN16-73-9797,에이서,1,인텔,9.0,외장,32.0,프리도스,90.0,2.450,16.0,2893000,7,"게임용 , 그래픽작업용",1,1,0,0,1,5.0
4,레노버 LEGION 5 15IRX10 i7 5060,레노버,0,인텔,7.0,외장,16.0,프리도스,80.0,1.900,15.1,1969000,43,"게임용 , 그래픽작업용",1,1,0,0,1,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,ASUS Gaming V16 V3607VM-RP006,ASUS,0,인텔,7.0,외장,16.0,프리도스,63.0,1.950,16.0,1755000,2,게임용,1,0,0,0,1,4.0
860,HP 오멘 MAX 16-ah0159TX,HP,1,인텔,9.0,외장,32.0,윈도우11,83.0,2.490,16.0,3145000,0,"게임용 , 그래픽작업용",1,1,0,0,0,0.0
861,LG전자 2024 그램 프로16 16ZD90SP-GX56K,LG전자,1,인텔,5.0,내장,16.0,프리도스,77.0,1.199,16.0,1805990,7,사무,0,0,1,0,1,5.0
862,LG전자 2023 울트라PC 15UD50R-GX56K WIN11,LG전자,0,인텔,5.0,내장,8.0,윈도우11,49.0,1.800,15.6,929230,4,사무,0,0,1,0,1,4.5
863,LG전자 2023 그램15 15ZD90RU-GX56K,LG전자,0,인텔,5.0,내장,16.0,프리도스,80.0,1.140,15.6,1553240,17,사무,0,0,1,0,1,4.8

In [ ]:
다나와2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 864 entries, 0 to 863
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   제품명         864 non-null    object
 1   브랜드         864 non-null    object
 2   AI여부        864 non-null    int64
 3   CPU브랜드      844 non-null    object
 4   CPU등급       831 non-null    float64
 5   그래픽         864 non-null    object
 6   RAM(GB)     864 non-null    float64
 7   OS          864 non-null    object
 8   배터리용량       864 non-null    float64
 9   무게(kg)      864 non-null    float64
 10  화면크기(인치)    864 non-null    float64
 11  가격          864 non-null    int64
 12  리뷰수         864 non-null    int64
 13  용도          864 non-null    object
 14  용도_게임용      864 non-null    int64
 15  용도_그래픽작업용   864 non-null    int64
 16  용도_사무       864 non-null    int64
 17  용도_휴대용      864 non-null    int64
 18  has_rating  864 non-null    int64
 19  별점          864 non-null    float64
dtypes: float64(6), int64(8), object(6)
memory usage: 135.1+ KB

In [ ]:
cpu_grade_map = {
    # 애플 M 시리즈 (CPU브랜드가 'APPLE'인 경우)
    #'M2': 5, 'M4': 7, 'M5': 9,
}
다나와2['CPU등급'] = 다나와2['CPU등급'].map(cpu_grade_map)

# 확인
다나와2

## 애플 cpu
- cpu 이름 애플로 채우기
- 제품이름에서 추출한 칩셋 등급을 챗봇의 도움을 받아 라이젠과 인텔의 cpu와 함께 3,5,7,9 등급을 맞춰 카테고리화

In [ ]:
import re

def extract_apple_cpu(name):
    match = re.search(r'(M\d)(프로|맥스|울트라)?', name)
    if match:
        chip = match.group(1)           # M2, M3, M4, M5
        variant = match.group(2) or ''  # 프로, 맥스, 울트라, 없으면 빈 문자열
        return chip + variant
    return None

apple_mask = 다나와2['브랜드'] == 'APPLE'

# CPU브랜드 채우기
다나와2.loc[apple_mask, 'CPU브랜드'] = 'APPLE'

# CPU등급 채우기
다나와2.loc[apple_mask, 'CPU등급'] = 다나와2.loc[apple_mask, '제품명'].apply(extract_apple_cpu)

/tmp/ipykernel_151/3425229310.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['M5프로' 'M5' 'M5프로' 'M5프로' 'M5' 'M5' 'M5프로' 'M3프로' 'M5' 'M5' 'M3' 'M4프로'
 'M2' 'M4프로' 'M5' 'M5']' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  다나와2.loc[apple_mask, 'CPU등급'] = 다나와2.loc[apple_mask, '제품명'].apply(extract_apple_cpu)

In [ ]:
cpu_grade_map.update({
    'M2': 5, 'M3': 5,
    'M3프로': 7, 'M4프로': 7, 'M5프로': 7,
    'M4': 7,
    'M5': 7,
    'M5맥스': 9, 'M5울트라': 9,
})

In [ ]:
다나와2

,제품명,브랜드,AI여부,CPU브랜드,CPU등급,그래픽,RAM(GB),OS,배터리용량,무게(kg),화면크기(인치),가격,리뷰수,용도,용도_게임용,용도_그래픽작업용,용도_사무,용도_휴대용,has_rating,별점
0,LG전자 2026 그램 프로16 16Z90U-KU7WK,LG전자,1,인텔,7.0,내장,32.0,윈도우11,77.0,1.190,16.0,3199000,102,사무,0,0,1,0,1,4.9
1,LG전자 2025 그램 프로16 16Z90TS-GU7WK,LG전자,1,인텔,7.0,내장,32.0,윈도우11,77.0,1.199,16.0,2489990,148,사무,0,0,1,0,1,4.9
2,HP 오멘 16-ap0117AX,HP,0,AMD,9.0,외장,32.0,프리도스,83.0,2.350,16.0,2399000,31,"게임용 , 그래픽작업용",1,1,0,0,1,4.8
3,에이서 프레데터 헬리오스 네오 16 AI PHN16-73-9797,에이서,1,인텔,9.0,외장,32.0,프리도스,90.0,2.450,16.0,2893000,7,"게임용 , 그래픽작업용",1,1,0,0,1,5.0
4,레노버 LEGION 5 15IRX10 i7 5060,레노버,0,인텔,7.0,외장,16.0,프리도스,80.0,1.900,15.1,1969000,43,"게임용 , 그래픽작업용",1,1,0,0,1,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,ASUS Gaming V16 V3607VM-RP006,ASUS,0,인텔,7.0,외장,16.0,프리도스,63.0,1.950,16.0,1755000,2,게임용,1,0,0,0,1,4.0
860,HP 오멘 MAX 16-ah0159TX,HP,1,인텔,9.0,외장,32.0,윈도우11,83.0,2.490,16.0,3145000,0,"게임용 , 그래픽작업용",1,1,0,0,0,0.0
861,LG전자 2024 그램 프로16 16ZD90SP-GX56K,LG전자,1,인텔,5.0,내장,16.0,프리도스,77.0,1.199,16.0,1805990,7,사무,0,0,1,0,1,5.0
862,LG전자 2023 울트라PC 15UD50R-GX56K WIN11,LG전자,0,인텔,5.0,내장,8.0,윈도우11,49.0,1.800,15.6,929230,4,사무,0,0,1,0,1,4.5
863,LG전자 2023 그램15 15ZD90RU-GX56K,LG전자,0,인텔,5.0,내장,16.0,프리도스,80.0,1.140,15.6,1553240,17,사무,0,0,1,0,1,4.8

In [ ]:
다나와2

,제품명,브랜드,AI여부,CPU브랜드,CPU등급,그래픽,RAM(GB),OS,배터리용량,무게(kg),화면크기(인치),가격,리뷰수,용도,용도_게임용,용도_그래픽작업용,용도_사무,용도_휴대용,has_rating,별점
0,LG전자 2026 그램 프로16 16Z90U-KU7WK,LG전자,1,인텔,7.0,내장,32.0,윈도우11,77.0,1.190,16.0,3199000,102,사무,0,0,1,0,1,4.9
1,LG전자 2025 그램 프로16 16Z90TS-GU7WK,LG전자,1,인텔,7.0,내장,32.0,윈도우11,77.0,1.199,16.0,2489990,148,사무,0,0,1,0,1,4.9
2,HP 오멘 16-ap0117AX,HP,0,AMD,9.0,외장,32.0,프리도스,83.0,2.350,16.0,2399000,31,"게임용 , 그래픽작업용",1,1,0,0,1,4.8
3,에이서 프레데터 헬리오스 네오 16 AI PHN16-73-9797,에이서,1,인텔,9.0,외장,32.0,프리도스,90.0,2.450,16.0,2893000,7,"게임용 , 그래픽작업용",1,1,0,0,1,5.0
4,레노버 LEGION 5 15IRX10 i7 5060,레노버,0,인텔,7.0,외장,16.0,프리도스,80.0,1.900,15.1,1969000,43,"게임용 , 그래픽작업용",1,1,0,0,1,4.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,ASUS Gaming V16 V3607VM-RP006,ASUS,0,인텔,7.0,외장,16.0,프리도스,63.0,1.950,16.0,1755000,2,게임용,1,0,0,0,1,4.0
860,HP 오멘 MAX 16-ah0159TX,HP,1,인텔,9.0,외장,32.0,윈도우11,83.0,2.490,16.0,3145000,0,"게임용 , 그래픽작업용",1,1,0,0,0,0.0
861,LG전자 2024 그램 프로16 16ZD90SP-GX56K,LG전자,1,인텔,5.0,내장,16.0,프리도스,77.0,1.199,16.0,1805990,7,사무,0,0,1,0,1,5.0
862,LG전자 2023 울트라PC 15UD50R-GX56K WIN11,LG전자,0,인텔,5.0,내장,8.0,윈도우11,49.0,1.800,15.6,929230,4,사무,0,0,1,0,1,4.5
863,LG전자 2023 그램15 15ZD90RU-GX56K,LG전자,0,인텔,5.0,내장,16.0,프리도스,80.0,1.140,15.6,1553240,17,사무,0,0,1,0,1,4.8

In [ ]:
다나와2['외장그래픽'] = (다나와2['그래픽'] == '외장').astype(int)

/tmp/ipykernel_151/1821454691.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  다나와2['외장그래픽'] = (다나와2['그래픽'] == '외장').astype(int)

# 내장외장 불리언값 저장 열 추가

In [ ]:
다나와2 = 다나와2.copy()
다나와2['외장그래픽'] = (다나와2['그래픽'] == '외장').astype(int)

In [ ]:
다나와2.to_csv('danawa2.csv', index=False, encoding='utf-8-sig')